import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '../components/header/header';

const Home: NextPage = () => {
  return (
    <div className="flex flex-col justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      {/* <div className="flex items-center justify-center bg-gray-800 p-6">
        <p>{`Welcome to  the Interval Workout App.`}</p>
      </div> */}
    </div>
  );
};

export default Home;
